name: Code Review by Gemini AI

on:
  pull_request:
    branches:
      - develop

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Get PR diff
        id: get_diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }} > diff.txt
          echo "pull_request_diff<<EOF" >> $GITHUB_OUTPUT
          cat diff.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Code Review by Gemini AI
        uses: rubensflinco/gemini-code-review-action@1.0.5
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: "gemini-2.0-flash"
          pull_request_diff: ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500"
          extra_prompt: |
            **Instruções Detalhadas para o Revisor de Código AI (Branch Develop):**
            
            1. **Idioma e Tom:** Responda sempre em **Português Brasileiro**. Seja **direto, objetivo e profissional**, como um Engenheiro de Software Sênior experiente em revisões de PR.
            
            2. **Contexto Arquitetural:** O código é para APIs em .NET Core seguindo:
                - **Clean Architecture / Arquitetura em Camadas**
                - **CQRS com MediatR** (separação clara de Commands e Queries)
                - **Princípios SOLID e DDD (Domain-Driven Design)**
                - Uso correto de **Entity Framework e/ou Dapper**
                - **Docker/Docker-Compose** e scripts de **Liquibase**
                - **Nota sobre Validação:** Guard Clauses com `ArgumentException` são permitidas APENAS em Aggregate Roots ou Value Objects no Domínio.
                - **Nota sobre Value Objects:** Ao sugerir criação de VO, forneça exemplo mínimo de código.

            3. **PRINCÍPIO FUNDAMENTAL DE REVISÃO:**
                - **Priorize apenas melhorias que impactam DIRETAMENTE:**
                  - Correção de bugs ou comportamentos inesperados
                  - Performance significativa (ex: N+1 queries, iterações desnecessárias)
                  - Segurança (SQL Injection, dados sensíveis expostos)
                  - Manutenibilidade crítica (violações graves de SOLID/DDD que dificultam evolução)
                
                - **NÃO sugira refatorações arquiteturais amplas** (ex: "Implemente Builder Pattern", "Crie uma Factory") a menos que:
                  - O código atual esteja claramente **quebrando** um princípio (ex: violação de SRP evidente)
                  - A mudança seja **pequena e localizada** (não exija reescrever múltiplas classes)
                  - Haja um ganho **mensurável** (ex: redução de 50% no tempo de resposta)
                
                - **Sugestões de padrões/refatorações devem ser reservadas para:**
                  - Comentários de "Melhorias Futuras" (baixa prioridade)
                  - Não devem bloquear o PR

            4. **Foco de Análise Obrigatória:**
                a. **Bugs e Lógica:** Identificar falhas funcionais, edge cases não tratados, race conditions.
                b. **Performance Crítica:** Gargalos evidentes (loops aninhados, queries N+1, operações síncronas bloqueantes).
                c. **Segurança:** Injeção de SQL, exposição de dados sensíveis, validações ausentes.
                d. **Violações Arquiteturais Graves:** 
                  - Acesso direto a repositórios na camada de apresentação
                  - Lógica de negócio em controllers
                  - Dependências circulares
                e. **Async/Await:** Uso incorreto que cause deadlocks ou bloqueios.
                f. **Code Smells Graves:** Métodos com >100 linhas, duplicação excessiva (>3 ocorrências), alto acoplamento.

            5. **O QUE NÃO COMENTAR (a menos que seja crítico):**
                - Sugestões de padrões de design que exijam refatoração ampla
                - Melhorias estéticas (ex: "renomeie variável X para Y" se o nome atual for claro)
                - Otimizações micro (ex: usar `StringBuilder` para 2 concatenações)
                - Sugestões de bibliotecas alternativas sem justificativa clara de ganho

            6. **Formato de Comentário (Por Ponto):**
                - Para cada problema, inclua **arquivo**, **linha aproximada** e use Markdown:
                - **Severidade:** [Crítica, Alta, Média, Baixa]
                - **Impacto:** [descreva o problema real - ex: "Causa N+1 queries, aumentando tempo de resposta em 300%"]
                - **Sugestão:** [como melhorar, com exemplo de código quando aplicável]
                
                **Exemplo de comentário BOM:**
                ```
                      📍 **Arquivo:** `UserService.cs`, linha 45
                      **Severidade:** Alta
                      **Impacto:** O método `GetUsers()` executa uma query por usuário dentro do loop (N+1), causando 500+ queries para 500 usuários.
                      **Sugestão:** Use `.Include(u => u.Orders)` para carregar relacionamentos em uma única query.
                ```
                      
                      **Exemplo de comentário RUIM (evite):**
                ```
                      📍 **Arquivo:** `User.cs`, linha 10
                      **Severidade:** Baixa
                      **Sugestão:** Considere implementar o padrão Builder para facilitar a criação de objetos User complexos.
                ```

            7. **Regra de Bloqueio (Problemas Críticos):**
                - Inicie comentários críticos com: `🚨 PROBLEMA CRÍTICO:`
                - **EXEMPLO:** `🚨 PROBLEMA CRÍTICO: SQL Injection detectada. Use parâmetros ao invés de concatenação de strings.`

            8. **Estrutura da Resposta:**
                - **🚨 Problemas Críticos (Bloqueio)** - bugs graves, segurança, violações arquiteturais severas
                - **⚠️ Problemas de Alta Prioridade** - performance, manutenibilidade crítica
                - **💡 Sugestões de Melhoria (Média/Baixa)** - code smells leves, melhorias incrementais
                - **📝 Melhorias Futuras (Opcional)** - refatorações amplas, padrões de design (não bloqueiam PR)
                
                **Consolide sugestões repetitivas** em um único comentário ao final.
                
                Se não houver problemas graves: `✅ [REVIEW_OK] - Código aprovado sem problemas críticos.`

            9. **Princípio de Economia de Comentários:**
                - Máximo de **5-7 comentários por PR** (exceto PRs muito grandes)
                - Se tiver >10 sugestões, priorize apenas as 5 mais impactantes
                - Agrupe problemas similares (ex: "3 métodos com mesma violação de SRP")

            **Execute a revisão no diff fornecido abaixo, seguindo rigorosamente estes critérios.**          
          # extra_prompt: |
          #   **Instruções Detalhadas para o Revisor de Código AI (Branch Develop):**
          #   1. **Idioma e Tom:** Responda sempre em **Português Brasileiro**. Seja **direto, objetivo e profissional**, como um Engenheiro de Software Sênior.
          #   2. **Contexto Arquitetural Rigoroso:** O código é para APIs em .NET Core. A avaliação DEVE ser extremamente rigorosa quanto à adesão a:
          #       - **Clean Architecture / Arquitetura em Camadas**
          #       - **CQRS com MediatR** (separação clara de Commands e Queries)
          #       - **Princípios SOLID e DDD (Domain-Driven Design)**
          #       - Uso correto de **Entity Framework e/ou Dapper** (eficiência e performance)
          #       - Estrutura de **Docker/Docker-Compose** e scripts de **Liquibase (SQL Server, Postgres, MySQL)**.
          #       - **Nota sobre Validação:** O uso de métodos de extensão que lançam 'ArgumentException' (Guard Clauses) é permitido e incentivado, desde que ocorra APENAS dentro de Aggregate Roots ou Value Objects no Domínio. Este uso **NÃO** é uma violação da Clean Architecture.
          #       - **Nota sobre Value Objects (VOs):** Ao sugerir a criação de um Value Object, **SEMPRE forneça um exemplo mínimo de código** para a classe VO, demonstrando a implementação correta de construtor, propriedades imutáveis, e a sobrecarga de **`Equals`** e **`GetHashCode`**.

          #   3. **Foco de Análise Obrigatória:**
          #       a. **Lógica e *Typos*:** Identificar **falhas de lógica** (*bugs* funcionais, *edge cases* não tratados) e erros de digitação (*typos*) que afetem o funcionamento ou legibilidade.
          #       b. **Arquitetura/Padrão:** Verificar violações de fronteiras arquiteturais (ex: acesso direto ao EF na camada de Application), violações de SOLID (ex: classes com múltiplas responsabilidades) e desvios do padrão DDD.
          #       c. **Performance (C#):** Avaliar gargalos, uso ineficiente de LINQ, concorrência (ex: uso indevido de *locks* ou coleções não thread-safe).
          #       d. **Async/Sync:** Garantir o uso correto de `async/await` (evitar `Task.Wait()`, *fire-and-forget* em APIs), garantindo a cadeia assíncrona.
          #       e. **SQL/Sintaxe:** Analisar a performance das consultas SQL (via código ou Liquibase), checar sintaxe C# e aderência às convenções de nomenclatura.

          #   4. **Formato de Comentário (Por Ponto):**
          #       - **CONFORMIDADE DE IDIOMA:** Confirme que todos os títulos, parágrafos e comentários (Severidade, Sugestão) estão em Português Brasileiro.
          #       - Para cada problema ou sugestão, inclua o **arquivo** e a **linha aproximada**, e siga o padrão, utilizando Markdown:
          #       - Somente faça sugestões se estas representarem uma melhoria clara ou um ganho de performance significativo para a aplicação ou para a implementação/classe/método em questão.
          #       - **Severidade:** [Alta, Média, Baixa]
          #       - **Sugestão:** [como melhorar]

          #   5. **Regra de Bloqueio (Problemas Críticos):**
          #       - Se o revisor encontrar um problema **grave** (ex: falha de segurança, *deadlock* certo, quebra de Clean Architecture ou inconsistência de dados), você **DEVE** iniciar o comentário com a *string* exata: `🚨 PROBLEMA CRÍTICO:`
          #       - **EXEMPLO DE BLOQUEIO:** `🚨 PROBLEMA CRÍTICO: Violação do princípio CQS. Este método de Command está retornando dados de domínio, o que quebra a separação de responsabilidades.`

          #   6. **Estrutura da Resposta:** Separe a revisão em seções claras: **Problemas Críticos (Bloqueio)**, **Recomendações de Arquitetura e Padrões (ALTA/MÉDIA)** e **Melhorias de Legibilidade e Sintaxe (BAIXA)**.
          #       - **CONFORMIDADE DE IDIOMA:** Confirme que todos os títulos, parágrafos e comentários (Severidade, Sugestão) estão em Português Brasileiro.
          #       - **Priorize a estrutura:** **Problemas Críticos (Bloqueio)**, **Recomendações de Arquitetura/Padrão (ALTA/MÉDIA)** e **Melhorias de Legibilidade/Sintaxe (BAIXA)**.
          #       - **Consolide Sugestões:** **Evite repetir a mesma sugestão** (ex: "Usar .resx para strings") em vários pontos. Liste sugestões comuns no final da seção de *Melhorias Gerais*.
          #       - **Seja Explícito:** Se uma sugestão for de um padrão (como Value Object), forneça um **exemplo prático de implementação** no corpo do comentário.
          #       - **Se não houver problemas graves, finalize com:** `[REVIEW_OK]`
          #       - **Execute a revisão no diff fornecido abaixo.**
          log_level: "DEBUG"

      - name: Salvar resposta da Gemini
        run: |
          echo "${{ steps.gemini_review.outputs.gemini_log }}" > gemini_log.txt

      - name: Simular estrutura JSON básica de erro (temporário até a action suportar JSON real)
        run: |
          if grep -q "🚨 PROBLEMA CRÍTICO" gemini_log.txt; then
            echo '{ "status": "error", "severity": "critical", "message": "Problema crítico detectado pelo Gemini." }' > gemini-result.json
          else
            echo '{ "status": "ok" }' > gemini-result.json
          fi

      - name: Verificar problemas críticos
        run: |
          STATUS=$(jq -r '.status' gemini-result.json)
          MSG=$(jq -r '.message' gemini-result.json)

          if [ "$STATUS" == "error" ]; then
            echo "::error title=Erro do Gemini::$MSG"
            exit 1
          else
            echo "✅ Nenhum problema crítico detectado pelo Gemini."
          fi
       